stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'windows-latest'

resources:
  repositories:
  - repository: test # The name used to reference this repository in the checkout step
    type: github
    endpoint: github.com_Bhoomi-P
    name: Bhoomi-P/testing
    branch: dev

steps:
- checkout: self
- script: dir $(Build.SourcesDirectory)


- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'drop'
    publishLocation: 'pipeline'

- stage: dev_deploy
  jobs:
  - deployment: dev_deploy
        pool:
      vmImage: 'windows-latest'

resources:
  repositories:
  - repository: test # The name used to reference this repository in the checkout step
    type: github
    endpoint: github.com_Bhoomi-P
    name: Bhoomi-P/testing
    branch: dev

steps:
- checkout: self
- script: dir $(Build.SourcesDirectory)


- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'drop'
    publishLocation: 'pipeline'

- stage: qa_deploy
  jobs:
  - deployment: qa_deploy
    pool:
      vmImage: 'windows-latest'

resources:
  repositories:
  - repository: test # The name used to reference this repository in the checkout step
    type: github
    endpoint: github.com_Bhoomi-P
    name: Bhoomi-P/testing
    branch: dev

steps:
- checkout: self
- script: dir $(Build.SourcesDirectory)


- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'drop'
    publishLocation: 'pipeline'